### PR TITLE
Pk/pre commit add

### PR DESCRIPTION
**Pull request by Pradyumnakashyap**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(use the format `fixes #<issue number>(, fixes #<issue_number>, ...)` to automatically close the issue when PR gets merged)*:
fixes #

**Public facing documentation PR** *(if applicable)*

**Special notes for reviewer**:

**Checklist:**

- [X] Added relevant notes to [WIP-CHANGELOG.md](https://github.com/elastisys/ck8s-cluster/blob/master/WIP-CHANGELOG.md)
- [X] Proper commit message prefix on all commits
- [ ] Updated the [public facing documentation](https://github.com/elastisys/compliantkubernetes)
- Is this changeset backwards compatible for existing clusters? Applying:
    - [X] is completely transparent, will not impact the workload in any way.
    - [ ] requires running a migration script.
    - [ ] will create noticeable cluster degradation.
          E.g. logs or metrics are not being collected or Kubernetes API server
          will not be responding while upgrading.
    - [ ] requires draining and/or replacing nodes.
    - [ ] will change any APIs.
          E.g. removes or changes any CK8S config options or Kubernetes APIs.
    - [ ] will break the cluster.
          I.e. full cluster migration is required.

### CODE REVIEW

**Comment by Pradyumnakashyap** [comment]
See a few formatting errors in the code leading to pre-commit failure. 
Help is welcome as I do not already have a company laptop :)

**Review by simonklb — CHANGES_REQUESTED** [review]
We already have a [pre-commit configuration](https://github.com/elastisys/ck8s-cluster/blob/master/.pre-commit-config.yaml) in this repo. Mind adding shellcheck to it instead and add a separate PR to run the pre-commit as part of the [test pipeline](https://github.com/elastisys/ck8s-cluster/blob/master/.github/workflows/pipeline.yml)?

**Comment by danielharr** [comment]
> We already have a [pre-commit configuration](https://github.com/elastisys/ck8s-cluster/blob/master/.pre-commit-config.yaml) in this repo. Mind adding shellcheck to it instead and add a separate PR to run the pre-commit as part of the [test pipeline](https://github.com/elastisys/ck8s-cluster/blob/master/.github/workflows/pipeline.yml)?

This PR adds pre-commit as part of the test pipeline. It's not adding a new .pre-commit-config.yaml, just for clarification :slightly_smiling_face:

**Comment by simonklb** [comment]
> > We already have a [pre-commit configuration](https://github.com/elastisys/ck8s-cluster/blob/master/.pre-commit-config.yaml) in this repo. Mind adding shellcheck to it instead and add a separate PR to run the pre-commit as part of the [test pipeline](https://github.com/elastisys/ck8s-cluster/blob/master/.github/workflows/pipeline.yml)?
> 
> This PR adds pre-commit as part of the test pipeline. It's not adding a new .pre-commit-config.yaml, just for clarification

Absolutely! I was just curious why there had to be two different workflow configs. But it's fine with me either way!

**Review by simonklb — CHANGES_REQUESTED** [review]
Please squash:
* the pre-commit config change and the indendation typo 
* the formatting and the warning/error fixes

**Review by simonklb — CHANGES_REQUESTED** [review]
I believe you have to install go and goimports for the pre-commit hooks to run properly as well, right now they are green because the binaries are missing I think.

Please verify that it actually checks for badly formatted go code and/or missing imports.

**Comment by danielharr** [comment]
> Please verify that it actually checks for badly formatted go code and/or missing imports.

Good catch! Verified both gofmt and goimports :slightly_smiling_face:

**Review by simonklb — APPROVED** [review]
Nice! Tested with pipeline/simulate.bash and no errors after the bash code changed at least. :smile:

**Pull request merged**
